# Site settings
language: 'en-in'
timezone: Asia/Kolkata

# Your details
title: Ram Iyer’s Résumé
description: Ram Iyer’s online résumé

name: "Ramakrishnan R.&hairsp;Iyer" # Your full name here
address: "513, 19<sup>th</sup> Cross, Purnapragna Layout, Bangalore, KA 560061"
email: "&#114;&#097;&#109;&#046;&#105;&#121;&#101;&#114;&#064;&#111;&#117;&#116;&#108;&#111;&#111;&#107;&#046;&#105;&#110;" # Encoded in order to prevent spam
phone: "+918861065751"
website: ramiyer.me

baseurl: /
url: "//about.ramiyer.me" # the base hostname & protocol for your site
twitter_username: theramiyer
github_username:  theramiyer

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

# Permalinks
permalink: :title

collections_dir: data
collections:
  experience:
    name: Experience
    output: true
    permalink: /:collection/:name/
    sequence: 1
  achievements:
    name: Achievements
    displayname: Achievements and Certifications
    output: true
    permalink: /:collection/:name/
    sequence: 2
  education:
    name: Education
    output: true
    permalink: /:collection/:name/
    sequence: 3
  extracurricular:
    name: Extracurricular
    output: true
    permalink: /:collection/:name/
    sequence: 4
